#docker roles/docker/tasks/main.yml

---
- name: Update system packages
  yum:
    name: "*"
    state: latest

- name: Install Git
  yum:
    name: git
    state: present

- name: Install Amazon Corretto 17 (Java 17)
  yum:
    name: java-17-amazon-corretto
    state: present

- name: Install Docker
  yum:
    name: docker
    state: present

- name: Start and enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started

- name: Add ec2-user to docker group
  user:
    name: ec2-user
    groups: docker
    append: yes

- name: Add Docker alias to ec2-user .bashrc
  lineinfile:
    path: /home/ec2-user/.bashrc
    line: "alias docker='sudo docker'"
    state: present
    create: yes
    owner: ec2-user
    group: ec2-user

- name: Reload bashrc
  shell: source /home/ec2-user/.bashrc
  args:
    executable: /bin/bash
