---
- name: Install Nginx using yum
  yum:
    name: nginx
    state: present
  become: true

- name: Enable and start Nginx service
  systemd:
    name: nginx
    state: started
    enabled: yes
  become: true
