---
- name: Install and start Nginx on target host
  hosts: nginx
  become: yes
  tasks:
    - name: Install Nginx using yum
      yum:
        name: nginx
        state: present

    - name: Enable and start Nginx service
      systemd:
        name: nginx
        state: started
        enabled: yes
