---
- name: Generate SSH key and upload public key to S3
  hosts: k8s-workstation
  become: false
  tasks:
    - name: Generate RSA SSH key if it does not exist
      ansible.builtin.command: ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -C "kops-key" -N ""
      args:
        creates: ~/.ssh/id_rsa

    - name: Upload public key to S3 bucket
      ansible.builtin.command: aws s3 cp ~/.ssh/id_rsa.pub s3://final-project-1-k8s-store/kops-key.pub
