---
- name: Create Kubernetes Cluster with eksctl
  hosts: k8s-workstation
  become: no
  tasks:
    - name: Copy cluster.sh to k8s workstation
      copy:
        src: cluster.sh
        dest: /home/ec2-user/cluster.sh
        owner: ec2-user
        group: ec2-user
        mode: '0755'  # make it executable directly

    - name: Run EKSCTL create cluster script
      shell: /home/ec2-user/cluster.sh
      args:
        executable: /bin/bash
