---
- name: Create Kubernetes Cluster with eksctl
  hosts: k8s_workstation
  become: no
  tasks:
    - name: Copy the entire k8s-admin-setup directory to the k8s workstation
      copy:
        src: ../k8s-admin-setup
        dest: /home/ec2-user/
        owner: ec2-user
        group: ec2-user
        mode: '0755'              # Safe default for files
        directory_mode: '0755'    # Directories should be executable to allow cd
    
    - name: Make only cluster.sh executable
      file:
        path: /home/ec2-user/k8s-admin-setup/cluster.sh
        mode: '0755'
        owner: ec2-user
        group: ec2-user
    
    - name: Run cluster.sh to create EKS cluster
      shell: ./cluster.sh
      args:
        chdir: /home/ec2-user/k8s-admin-setup
        executable: /bin/bash
