---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatApp
  labels:
    app: chatApp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: chatApp
  template:
    metadata:
      labels:
        app: chatApp
    spec:
      containers:
        - name: chatApp
          image: ayoyinka/chatApp:1
          ports:
            - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: chatApp
spec:
  type: LoadBalancer
  selector:
    app: chatApp
  ports:
    - port: 3000
      targetPort: 3000
