---
- name: Check if amazon.aws collection is already installed
  ansible.builtin.shell: ansible-galaxy collection list | grep amazon.aws
  register: amazon_aws_check
  ignore_errors: true
  changed_when: false

- name: Install amazon.aws collection if missing
  ansible.builtin.command: ansible-galaxy collection install amazon.aws
  when: amazon_aws_check.rc != 0
